In [1]:
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from pathlib import Path
from data_scripts import *
import pandas as pd


NUM_SIMS = 20
CONVERGED = False
USE_SIMULATED_TIME = False

In [2]:
data = {
    # "Standard exploration": load_data('../1/poro_dynamic', n_newest=NUM_SIMS),
    r"Standard exploration $\varepsilon = 0.5$": load_data("poro_eps_default", n_newest=NUM_SIMS),
    r"No exploration $\varepsilon = 0$": load_data("poro_eps0", n_newest=NUM_SIMS),
    r"More exploration $\varepsilon = 0.7$": load_data("poro_eps_big", n_newest=NUM_SIMS),
    "Random choice": load_data('../1/poro_lrandom', n_newest=NUM_SIMS)
    # "GP": load_data("poro_gp", n_newest=NUM_SIMS),
}

times_dict = dict()
for name, values in data.items():
    times_dict[name] = []
    for perf in values:
        res = np.sum(
            sum_per_time_step(
                make_solve_linear_system_time(perf, converged=CONVERGED),
                perf,
                converged=CONVERGED,
            )
        )
        times_dict[name].append(res)


times = pd.DataFrame.from_dict(times_dict).T
new_data = {
    'Worst': times.max(axis=1),
    'Mean': times.mean(axis=1),
    'Best': times.min(axis=1),
}
df_mandel = pd.DataFrame.from_dict(new_data)
df_mandel

Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_default_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps0_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/poro_eps_big_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_30.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_31.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_32.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_33.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_34.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/poro_lrandom_49.npy

                                              Worst       Mean       Best
Standard exploration $\varepsilon = 0.5$  78.617018  76.627515  75.103371
No exploration $\varepsilon = 0$          89.396812  76.850925  73.619636
More exploration $\varepsilon = 0.7$      79.170894  77.127136  75.969868
Random choice                             90.152661  87.553706  85.777204

In [3]:
data = {
    "Standard from 1": load_data('../1/thermal_dynamic', n_newest=NUM_SIMS),
    r"Standard exploration $\varepsilon = 0.5$": load_data("thermal_eps_default", n_newest=NUM_SIMS),
    r"No exploration $\varepsilon = 0$": load_data("thermal_eps0", n_newest=NUM_SIMS),
    r"More exploration $\varepsilon = 0.7$": load_data("thermal_eps_big", n_newest=NUM_SIMS),
    "Random choice": load_data('../1/thermal_random', n_newest=NUM_SIMS)
    # "GP": load_data("thermal_gp", n_newest=NUM_SIMS),
}

times_dict = dict()
for name, values in data.items():
    times_dict[name] = []
    for perf in values:
        res = np.sum(
            sum_per_time_step(
                make_solve_linear_system_time(perf, converged=CONVERGED),
                perf,
                converged=CONVERGED,
            )
        )
        times_dict[name].append(res)


times = pd.DataFrame.from_dict(times_dict).T
new_data = {
    'Worst': times.max(axis=1),
    'Mean': times.mean(axis=1),
    'Best': times.min(axis=1),
}
df_thermal = pd.DataFrame.from_dict(new_data)
df_thermal

Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_30.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_31.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_32.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_33.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_34.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_dynamic_49.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_default_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps0_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_49.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_50.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_51.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_52.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_53.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/performance/thermal_eps_big_54.npy
Loading data:
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_30.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_31.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_32.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_33.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_34.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_35.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_36.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_37.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_38.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_39.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_40.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_41.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_42.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_43.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_44.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_45.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_46.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_47.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_48.npy
/home/porepy/solver_selector/examples/3_exploration_sensitivity/../1/performance/thermal_random_49.npy

                                               Worst        Mean        Best
Standard from 1                           149.456748  132.169523  123.435049
Standard exploration $\varepsilon = 0.5$  142.808875  131.581378  121.928150
No exploration $\varepsilon = 0$          149.597536  129.285216  120.697926
More exploration $\varepsilon = 0.7$      139.130606  130.126475  122.722917
Random choice                             225.151762  205.134579  167.358702

In [4]:
df = pd.concat((df_mandel, df_thermal), join='inner', axis=1, keys=("Mandel's problem", "Non-isothermal flow problem"))
df = df.style.highlight_min(axis=0, props="textbf:--rwrap;").format(precision=2)
df

In [5]:
print(df.to_latex(column_format=' l | rrr | rrr ', hrules=True))

\begin{tabular}{l | rrr | rrr}
\toprule
 & \multicolumn{3}{r}{Mandel's problem} & \multicolumn{3}{r}{Non-isothermal flow problem} \\
 & Worst & Mean & Best & Worst & Mean & Best \\
\midrule
Standard exploration $\varepsilon = 0.5$ & \textbf{78.62} & \textbf{76.63} & 75.10 & 142.81 & 131.58 & 121.93 \\
No exploration $\varepsilon = 0$ & 89.40 & 76.85 & \textbf{73.62} & 149.60 & \textbf{129.29} & \textbf{120.70} \\
More exploration $\varepsilon = 0.7$ & 79.17 & 77.13 & 75.97 & \textbf{139.13} & 130.13 & 122.72 \\
Random choice & 90.15 & 87.55 & 85.78 & 225.15 & 205.13 & 167.36 \\
\bottomrule
\end{tabular}